In [26]:
import cv2
import os

data_path = 'dataset'
categories = os.listdir(data_path)  #get folder


categories.remove('.DS_Store')

labels = [i for i in range(len(categories))]

label_dict = dict(zip(categories,labels)) #dictonary
print(label_dict)
print(categories)
print(labels)






print(categories)
print(label_dict)
print(labels)

{'mask_weared_incorrect': 0, 'with_mask': 1, 'without_mask': 2}
['mask_weared_incorrect', 'with_mask', 'without_mask']
[0, 1, 2]
['mask_weared_incorrect', 'with_mask', 'without_mask']
{'mask_weared_incorrect': 0, 'with_mask': 1, 'without_mask': 2}
[0, 1, 2]


In [27]:
img_size = 100
data = []
target = []

for category in categories:
    folder_path = os.path.join(data_path,category)
    img_names = os.listdir(folder_path)
    
    for img_name in img_names:
        img_path = os.path.join(folder_path,img_name)
        img = cv2.imread(img_path)
        
        try:
            gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
            #converting the image into gray scale
            resized = cv2.resize(gray,(img_size,img_size))
            #resizing the gray scale into 100*100,since we need a fixed common size for all the images in the dataset
            data.append(resized)
            target.append(label_dict[category])
            #appending the image and the label (categorized) into the list
            
        except Exception as e:
            print("Exception:",e)
            #if any exception raised,the exception will be printed here. And pass to the next image

Exception: OpenCV(4.9.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Exception: OpenCV(4.9.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'



In [28]:
target

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [29]:
import numpy as np

data = np.array(data)/255.0  #normalization
print(data.shape)
data = np.reshape(data,(data.shape[0],img_size,img_size,1))
target = np.array(target)

#from tensorflow.keras.utils import to_categorical

#from keras.utils import np_utils
from tensorflow.keras.utils import to_categorical

new_target = to_categorical(target)
print(new_target)


(6197, 100, 100)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [32]:
new_target

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)

In [31]:
np.save('data',data)
np.save('target',new_target)

Certainly! This code snippet utilizes a function from Keras' utils module called to_categorical, specifically np_utils.to_categorical, to convert target labels into categorical format.
Here's a breakdown of what the code does:
Importing Libraries:
from keras.utils import np_utils imports the np_utils module from Keras utilities, which contains various helper functions. Conversior, to Categorical:
np_utils.to_ categorical(target) takes an array of target labels (target) and converts it into a categorical format. Categorical encoding converts class labels from integers to a one-hot encoded representation. For instance, if you have labels like [0, 1, 2), after conversic on, - they would look like: 0 becomes [1, 0, O] 1 becomes [0, 1, 0] 2 becomes [0, 0, 1] Printing the Converted Labels: print(new_target) displays the converted categorical representation of the target labels (new target) in the console. This conversion is commonly used in machine learning tasks, especially when dealing with classification problems, to represent class labels in a formal that is suitable for training neural networks or other machine learning models


