In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
          'amazing restaurant',
          'too good',
           'just loved it!',
           'will go again',
           'horrible food',
           'never go there',
           'poor service',
           'poor quality',
           'needs improvement']
sentiment=np.array([1,1,1,1,1,0,0,0,0,0])



2024-03-05 15:09:47.570351: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
one_hot('amazing restaurant', 30)

[19, 1]

In [3]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]

In [4]:
max_length=4
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[ 4 27  0  0]
 [19  1  0  0]
 [15  2  0  0]
 [13 23  3  0]
 [28 27 28  0]
 [10 27  0  0]
 [19 27  5  0]
 [11 24  0  0]
 [11 20  0  0]
 [13 13  0  0]]


In [5]:
embedded_vector_size=5

model=Sequential()
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [6]:
x=padded_reviews
y=sentiment

In [7]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171 (684.00 Byte)
Trainable params: 171 (684.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [8]:
model.fit(x,y,epochs=50,verbose=0)

In [9]:
#evaluate the model
loss,accuracy=model.evaluate(x,y)
accuracy

1/1 [==============================] - 0s 159ms/step - loss: 0.6301 - accuracy: 1.0000


1.0

In [10]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [11]:
weights[13]

array([-0.0961096 , -0.04298145, -0.08736581,  0.04035201,  0.03657729],
      dtype=float32)

In [13]:
weights[16]

array([ 0.03089017,  0.04166413,  0.0327921 , -0.03653215,  0.00218916],
      dtype=float32)